// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: api/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ApiService_Chat_FullMethodName         = "/llmapi.api.v1.ApiService/Chat"
	ApiService_ChatStream_FullMethodName   = "/llmapi.api.v1.ApiService/ChatStream"
	ApiService_ChatRealtime_FullMethodName = "/llmapi.api.v1.ApiService/ChatRealtime"
)

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (ApiService_ChatStreamClient, error)
	ChatRealtime(ctx context.Context, opts ...grpc.CallOption) (ApiService_ChatRealtimeClient, error)
}

type apiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServiceClient(cc grpc.ClientConnInterface) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, ApiService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (ApiService_ChatStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApiService_ServiceDesc.Streams[0], ApiService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &apiServiceChatStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ApiService_ChatStreamClient interface {
	Recv() (*ChatStreamResponse, error)
	grpc.ClientStream
}

type apiServiceChatStreamClient struct {
	grpc.ClientStream
}

func (x *apiServiceChatStreamClient) Recv() (*ChatStreamResponse, error) {
	m := new(ChatStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiServiceClient) ChatRealtime(ctx context.Context, opts ...grpc.CallOption) (ApiService_ChatRealtimeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApiService_ServiceDesc.Streams[1], ApiService_ChatRealtime_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &apiServiceChatRealtimeClient{ClientStream: stream}
	return x, nil
}

type ApiService_ChatRealtimeClient interface {
	Send(*ChatRealtimeRequest) error
	Recv() (*ChatRealtimeResponse, error)
	grpc.ClientStream
}

type apiServiceChatRealtimeClient struct {
	grpc.ClientStream
}

func (x *apiServiceChatRealtimeClient) Send(m *ChatRealtimeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *apiServiceChatRealtimeClient) Recv() (*ChatRealtimeResponse, error) {
	m := new(ChatRealtimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServiceServer is the server API for ApiService service.
// All implementations should embed UnimplementedApiServiceServer
// for forward compatibility
type ApiServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatStreamRequest, ApiService_ChatStreamServer) error
	ChatRealtime(ApiService_ChatRealtimeServer) error
}

// UnimplementedApiServiceServer should be embedded to have forward compatible implementations.
type UnimplementedApiServiceServer struct {
}

func (UnimplementedApiServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedApiServiceServer) ChatStream(*ChatStreamRequest, ApiService_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedApiServiceServer) ChatRealtime(ApiService_ChatRealtimeServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatRealtime not implemented")
}

// UnsafeApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServiceServer will
// result in compilation errors.
type UnsafeApiServiceServer interface {
	mustEmbedUnimplementedApiServiceServer()
}

func RegisterApiServiceServer(s grpc.ServiceRegistrar, srv ApiServiceServer) {
	s.RegisterService(&ApiService_ServiceDesc, srv)
}

func _ApiService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServiceServer).ChatStream(m, &apiServiceChatStreamServer{ServerStream: stream})
}

type ApiService_ChatStreamServer interface {
	Send(*ChatStreamResponse) error
	grpc.ServerStream
}

type apiServiceChatStreamServer struct {
	grpc.ServerStream
}

func (x *apiServiceChatStreamServer) Send(m *ChatStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ApiService_ChatRealtime_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiServiceServer).ChatRealtime(&apiServiceChatRealtimeServer{ServerStream: stream})
}

type ApiService_ChatRealtimeServer interface {
	Send(*ChatRealtimeResponse) error
	Recv() (*ChatRealtimeRequest, error)
	grpc.ServerStream
}

type apiServiceChatRealtimeServer struct {
	grpc.ServerStream
}

func (x *apiServiceChatRealtimeServer) Send(m *ChatRealtimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *apiServiceChatRealtimeServer) Recv() (*ChatRealtimeRequest, error) {
	m := new(ChatRealtimeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiService_ServiceDesc is the grpc.ServiceDesc for ApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmapi.api.v1.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _ApiService_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _ApiService_ChatStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatRealtime",
			Handler:       _ApiService_ChatRealtime_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/api.proto",
}
